version: "3.9"

services:
    web:
        container_name: web
        build: .
        command: python manage.py runserver 0.0.0.0:3008
        volumes:
            - .:/code
        ports:
            - "3008:3008"
        networks:
            - red_ssbw
        extra_hosts:
            # To comunicate host with docker container
            - "host.docker.internal:host-gateway"


networks:
    red_ssbw: