version: "3.9"

services:
    web:
        container_name: web
        build: .
        #command: python manage.py runserver 0.0.0.0:3008
        #command: gunicorn senderos.wsgi:application --bind 0.0.0.0:3008
        command: python3 manage.py runserver 0.0.0.0:3008
        volumes:
            - .:/code
        ports:
            - "3008:3008"
        networks:
            - red_ssbw
        extra_hosts:
            # To comunicate host with docker container
            - "host.docker.internal:host-gateway"
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - 80:80
        networks:
            - red_ssbw
        volumes:
            - ./conf:/etc/nginx/conf.d/default.conf
            - ./static:/var/www/static
        depends_on:
            - web

networks:
    red_ssbw:
